
--CUSTOMER_SHARE_LOG table
CREATE TABLE lavetrina.CUSTOMER_SHARE_LOG(
  TRANSACTION_ID bigint(20) NOT NULL AUTO_INCREMENT,
  CHANNEL int(11) DEFAULT NULL,
  CUSTOMER_ID bigint(20) NOT NULL,
  TRANSACTION_DATE DATE NOT NULL,
  DISCOUNT_SENT boolean DEFAULT false,
  PRIMARY KEY (TRANSACTION_ID),
  UNIQUE KEY TRANSACTION_ID(TRANSACTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



--CUSTOMER_SOCIAL_DISCOUNT_HISTORY able
CREATE TABLE lavetrina.CUSTOMER_SOCIAL_DISCOUNT_HISTORY(
  TRANSACTION_ID bigint(20) NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID bigint(20) NOT NULL,
  COUPON VARCHAR(100) NOT NULL,
  DISCOUNT_PERCENTAGE INT NOT NULL,
  START_DATE DATE NOT NULL ,
  END_DATE DATE NOT NULL,
  CREATION_DATE  DATE NOT NULL,
  
  PRIMARY KEY (TRANSACTION_ID),
  UNIQUE KEY TRANSACTION_ID(TRANSACTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE VIEW lavetrina.CUSTOMER_SHARE_VIEW AS 
SELECT customer_share_log.CUSTOMER_ID AS CUSTOMER_ID ,
customer.customer_email_address AS CUSTOMER_EMAIL,
count(customer_share_log.TRANSACTION_ID) AS COUNT 
FROM lavetrina.customer_share_log,
lavetrina.customer 
WHERE 
DISCOUNT_SENT=0 
AND
customer.customer_id=customer_share_log.customer_id   
GROUP BY CUSTOMER_ID,customer_email_address